package com.yhq.sqlserver.pojo;

public class PaymentMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_payment_map.id
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_payment_map.wdid
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    private Integer wdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_payment_map.accountNo
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    private String accountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_payment_map.isWork
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    private Boolean iswork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_payment_map.enable_time
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    private String enableTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_payment_map.id
     *
     * @return the value of website_payment_map.id
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_payment_map.id
     *
     * @param id the value for website_payment_map.id
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_payment_map.wdid
     *
     * @return the value of website_payment_map.wdid
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    public Integer getWdid() {
        return wdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_payment_map.wdid
     *
     * @param wdid the value for website_payment_map.wdid
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    public void setWdid(Integer wdid) {
        this.wdid = wdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_payment_map.accountNo
     *
     * @return the value of website_payment_map.accountNo
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    public String getAccountno() {
        return accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_payment_map.accountNo
     *
     * @param accountno the value for website_payment_map.accountNo
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    public void setAccountno(String accountno) {
        this.accountno = accountno == null ? null : accountno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_payment_map.isWork
     *
     * @return the value of website_payment_map.isWork
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    public Boolean getIswork() {
        return iswork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_payment_map.isWork
     *
     * @param iswork the value for website_payment_map.isWork
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    public void setIswork(Boolean iswork) {
        this.iswork = iswork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_payment_map.enable_time
     *
     * @return the value of website_payment_map.enable_time
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    public String getEnableTime() {
        return enableTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_payment_map.enable_time
     *
     * @param enableTime the value for website_payment_map.enable_time
     *
     * @mbggenerated Fri Sep 23 12:47:47 CST 2016
     */
    public void setEnableTime(String enableTime) {
        this.enableTime = enableTime == null ? null : enableTime.trim();
    }
}