package com.yhq.sqlserver.pojo;

import java.io.Serializable;


public class WebsiteCal implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 7767230730096789676L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.id
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.CenterID
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String centerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.CZ_id
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String czId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.title
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.czStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String czstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.zgName
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String zgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.zgCheckWdStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String zgcheckwdstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.Status
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.serviceStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String servicestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.standardStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String standardstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.PPhone
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String pphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.OPhone
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String ophone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.starId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String starid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.leve
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String leve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.GradeId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String gradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.STypeId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String stypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.Area
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.LED
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String led;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.ZdAmount
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String zdamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.sellerRecord
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String sellerrecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.Begin_date
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.monthServiceCount
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String monthservicecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.serviceDate
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String servicedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.serviceEvaluation
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String serviceevaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.handlingPerson
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String handlingperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.zgGpStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String zggpstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.systemGpStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String systemgpstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.zgJcStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String zgjcstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.systemJcStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String systemjcstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.playPrompt
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String playprompt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.sale
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double sale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.jikaiSale
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double jikaisale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.notHalfYearItemScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double nothalfyearitemscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.wdZhongHeScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double wdzhonghescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.standardScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double standardscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.halfYearItemScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double halfyearitemscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.wdGradeScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double wdgradescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.wdSaleScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double wdsalescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.baseScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double basescore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.ltScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double ltscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.jcScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double jcscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.jkScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Double jkscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.monthDate
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String monthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.wdid
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private Integer wdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.cid
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_cal.userId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.id
     *
     * @return the value of wd_cal.id
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.id
     *
     * @param id the value for wd_cal.id
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.CenterID
     *
     * @return the value of wd_cal.CenterID
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getCenterid() {
        return centerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.CenterID
     *
     * @param centerid the value for wd_cal.CenterID
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setCenterid(String centerid) {
        this.centerid = centerid == null ? null : centerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.CZ_id
     *
     * @return the value of wd_cal.CZ_id
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getCzId() {
        return czId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.CZ_id
     *
     * @param czId the value for wd_cal.CZ_id
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setCzId(String czId) {
        this.czId = czId == null ? null : czId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.title
     *
     * @return the value of wd_cal.title
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.title
     *
     * @param title the value for wd_cal.title
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.czStatus
     *
     * @return the value of wd_cal.czStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getCzstatus() {
        return czstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.czStatus
     *
     * @param czstatus the value for wd_cal.czStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setCzstatus(String czstatus) {
        this.czstatus = czstatus == null ? null : czstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.zgName
     *
     * @return the value of wd_cal.zgName
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getZgname() {
        return zgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.zgName
     *
     * @param zgname the value for wd_cal.zgName
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setZgname(String zgname) {
        this.zgname = zgname == null ? null : zgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.zgCheckWdStatus
     *
     * @return the value of wd_cal.zgCheckWdStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getZgcheckwdstatus() {
        return zgcheckwdstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.zgCheckWdStatus
     *
     * @param zgcheckwdstatus the value for wd_cal.zgCheckWdStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setZgcheckwdstatus(String zgcheckwdstatus) {
        this.zgcheckwdstatus = zgcheckwdstatus == null ? null : zgcheckwdstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.Status
     *
     * @return the value of wd_cal.Status
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.Status
     *
     * @param status the value for wd_cal.Status
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.serviceStatus
     *
     * @return the value of wd_cal.serviceStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getServicestatus() {
        return servicestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.serviceStatus
     *
     * @param servicestatus the value for wd_cal.serviceStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setServicestatus(String servicestatus) {
        this.servicestatus = servicestatus == null ? null : servicestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.standardStatus
     *
     * @return the value of wd_cal.standardStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getStandardstatus() {
        return standardstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.standardStatus
     *
     * @param standardstatus the value for wd_cal.standardStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setStandardstatus(String standardstatus) {
        this.standardstatus = standardstatus == null ? null : standardstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.PPhone
     *
     * @return the value of wd_cal.PPhone
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getPphone() {
        return pphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.PPhone
     *
     * @param pphone the value for wd_cal.PPhone
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setPphone(String pphone) {
        this.pphone = pphone == null ? null : pphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.OPhone
     *
     * @return the value of wd_cal.OPhone
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getOphone() {
        return ophone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.OPhone
     *
     * @param ophone the value for wd_cal.OPhone
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setOphone(String ophone) {
        this.ophone = ophone == null ? null : ophone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.starId
     *
     * @return the value of wd_cal.starId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getStarid() {
        return starid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.starId
     *
     * @param starid the value for wd_cal.starId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setStarid(String starid) {
        this.starid = starid == null ? null : starid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.leve
     *
     * @return the value of wd_cal.leve
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getLeve() {
        return leve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.leve
     *
     * @param leve the value for wd_cal.leve
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setLeve(String leve) {
        this.leve = leve == null ? null : leve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.GradeId
     *
     * @return the value of wd_cal.GradeId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.GradeId
     *
     * @param gradeid the value for wd_cal.GradeId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setGradeid(String gradeid) {
        this.gradeid = gradeid == null ? null : gradeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.STypeId
     *
     * @return the value of wd_cal.STypeId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getStypeid() {
        return stypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.STypeId
     *
     * @param stypeid the value for wd_cal.STypeId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setStypeid(String stypeid) {
        this.stypeid = stypeid == null ? null : stypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.Area
     *
     * @return the value of wd_cal.Area
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.Area
     *
     * @param area the value for wd_cal.Area
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.LED
     *
     * @return the value of wd_cal.LED
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getLed() {
        return led;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.LED
     *
     * @param led the value for wd_cal.LED
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setLed(String led) {
        this.led = led == null ? null : led.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.ZdAmount
     *
     * @return the value of wd_cal.ZdAmount
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getZdamount() {
        return zdamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.ZdAmount
     *
     * @param zdamount the value for wd_cal.ZdAmount
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setZdamount(String zdamount) {
        this.zdamount = zdamount == null ? null : zdamount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.sellerRecord
     *
     * @return the value of wd_cal.sellerRecord
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getSellerrecord() {
        return sellerrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.sellerRecord
     *
     * @param sellerrecord the value for wd_cal.sellerRecord
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setSellerrecord(String sellerrecord) {
        this.sellerrecord = sellerrecord == null ? null : sellerrecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.Begin_date
     *
     * @return the value of wd_cal.Begin_date
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.Begin_date
     *
     * @param beginDate the value for wd_cal.Begin_date
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate == null ? null : beginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.monthServiceCount
     *
     * @return the value of wd_cal.monthServiceCount
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getMonthservicecount() {
        return monthservicecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.monthServiceCount
     *
     * @param monthservicecount the value for wd_cal.monthServiceCount
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setMonthservicecount(String monthservicecount) {
        this.monthservicecount = monthservicecount == null ? null : monthservicecount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.serviceDate
     *
     * @return the value of wd_cal.serviceDate
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getServicedate() {
        return servicedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.serviceDate
     *
     * @param servicedate the value for wd_cal.serviceDate
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setServicedate(String servicedate) {
        this.servicedate = servicedate == null ? null : servicedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.serviceEvaluation
     *
     * @return the value of wd_cal.serviceEvaluation
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getServiceevaluation() {
        return serviceevaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.serviceEvaluation
     *
     * @param serviceevaluation the value for wd_cal.serviceEvaluation
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setServiceevaluation(String serviceevaluation) {
        this.serviceevaluation = serviceevaluation == null ? null : serviceevaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.handlingPerson
     *
     * @return the value of wd_cal.handlingPerson
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getHandlingperson() {
        return handlingperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.handlingPerson
     *
     * @param handlingperson the value for wd_cal.handlingPerson
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setHandlingperson(String handlingperson) {
        this.handlingperson = handlingperson == null ? null : handlingperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.zgGpStatus
     *
     * @return the value of wd_cal.zgGpStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getZggpstatus() {
        return zggpstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.zgGpStatus
     *
     * @param zggpstatus the value for wd_cal.zgGpStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setZggpstatus(String zggpstatus) {
        this.zggpstatus = zggpstatus == null ? null : zggpstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.systemGpStatus
     *
     * @return the value of wd_cal.systemGpStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getSystemgpstatus() {
        return systemgpstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.systemGpStatus
     *
     * @param systemgpstatus the value for wd_cal.systemGpStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setSystemgpstatus(String systemgpstatus) {
        this.systemgpstatus = systemgpstatus == null ? null : systemgpstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.zgJcStatus
     *
     * @return the value of wd_cal.zgJcStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getZgjcstatus() {
        return zgjcstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.zgJcStatus
     *
     * @param zgjcstatus the value for wd_cal.zgJcStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setZgjcstatus(String zgjcstatus) {
        this.zgjcstatus = zgjcstatus == null ? null : zgjcstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.systemJcStatus
     *
     * @return the value of wd_cal.systemJcStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getSystemjcstatus() {
        return systemjcstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.systemJcStatus
     *
     * @param systemjcstatus the value for wd_cal.systemJcStatus
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setSystemjcstatus(String systemjcstatus) {
        this.systemjcstatus = systemjcstatus == null ? null : systemjcstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.playPrompt
     *
     * @return the value of wd_cal.playPrompt
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getPlayprompt() {
        return playprompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.playPrompt
     *
     * @param playprompt the value for wd_cal.playPrompt
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setPlayprompt(String playprompt) {
        this.playprompt = playprompt == null ? null : playprompt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.sale
     *
     * @return the value of wd_cal.sale
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.sale
     *
     * @param sale the value for wd_cal.sale
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setSale(Double sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.jikaiSale
     *
     * @return the value of wd_cal.jikaiSale
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getJikaisale() {
        return jikaisale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.jikaiSale
     *
     * @param jikaisale the value for wd_cal.jikaiSale
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setJikaisale(Double jikaisale) {
        this.jikaisale = jikaisale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.notHalfYearItemScore
     *
     * @return the value of wd_cal.notHalfYearItemScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getNothalfyearitemscore() {
        return nothalfyearitemscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.notHalfYearItemScore
     *
     * @param nothalfyearitemscore the value for wd_cal.notHalfYearItemScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setNothalfyearitemscore(Double nothalfyearitemscore) {
        this.nothalfyearitemscore = nothalfyearitemscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.wdZhongHeScore
     *
     * @return the value of wd_cal.wdZhongHeScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getWdzhonghescore() {
        return wdzhonghescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.wdZhongHeScore
     *
     * @param wdzhonghescore the value for wd_cal.wdZhongHeScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setWdzhonghescore(Double wdzhonghescore) {
        this.wdzhonghescore = wdzhonghescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.standardScore
     *
     * @return the value of wd_cal.standardScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getStandardscore() {
        return standardscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.standardScore
     *
     * @param standardscore the value for wd_cal.standardScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setStandardscore(Double standardscore) {
        this.standardscore = standardscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.halfYearItemScore
     *
     * @return the value of wd_cal.halfYearItemScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getHalfyearitemscore() {
        return halfyearitemscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.halfYearItemScore
     *
     * @param halfyearitemscore the value for wd_cal.halfYearItemScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setHalfyearitemscore(Double halfyearitemscore) {
        this.halfyearitemscore = halfyearitemscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.wdGradeScore
     *
     * @return the value of wd_cal.wdGradeScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getWdgradescore() {
        return wdgradescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.wdGradeScore
     *
     * @param wdgradescore the value for wd_cal.wdGradeScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setWdgradescore(Double wdgradescore) {
        this.wdgradescore = wdgradescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.wdSaleScore
     *
     * @return the value of wd_cal.wdSaleScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getWdsalescore() {
        return wdsalescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.wdSaleScore
     *
     * @param wdsalescore the value for wd_cal.wdSaleScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setWdsalescore(Double wdsalescore) {
        this.wdsalescore = wdsalescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.baseScore
     *
     * @return the value of wd_cal.baseScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getBasescore() {
        return basescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.baseScore
     *
     * @param basescore the value for wd_cal.baseScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setBasescore(Double basescore) {
        this.basescore = basescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.ltScore
     *
     * @return the value of wd_cal.ltScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getLtscore() {
        return ltscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.ltScore
     *
     * @param ltscore the value for wd_cal.ltScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setLtscore(Double ltscore) {
        this.ltscore = ltscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.jcScore
     *
     * @return the value of wd_cal.jcScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getJcscore() {
        return jcscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.jcScore
     *
     * @param jcscore the value for wd_cal.jcScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setJcscore(Double jcscore) {
        this.jcscore = jcscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.jkScore
     *
     * @return the value of wd_cal.jkScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Double getJkscore() {
        return jkscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.jkScore
     *
     * @param jkscore the value for wd_cal.jkScore
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setJkscore(Double jkscore) {
        this.jkscore = jkscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.monthDate
     *
     * @return the value of wd_cal.monthDate
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getMonthdate() {
        return monthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.monthDate
     *
     * @param monthdate the value for wd_cal.monthDate
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setMonthdate(String monthdate) {
        this.monthdate = monthdate == null ? null : monthdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.wdid
     *
     * @return the value of wd_cal.wdid
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public Integer getWdid() {
        return wdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.wdid
     *
     * @param wdid the value for wd_cal.wdid
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setWdid(Integer wdid) {
        this.wdid = wdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.cid
     *
     * @return the value of wd_cal.cid
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.cid
     *
     * @param cid the value for wd_cal.cid
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_cal.userId
     *
     * @return the value of wd_cal.userId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_cal.userId
     *
     * @param userid the value for wd_cal.userId
     *
     * @mbggenerated Fri Sep 23 12:48:48 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

}