package com.yhq.sqlserver.pojo;

public class WebsiteWithBLOBs extends Website {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1847069078301983175L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd.wdRemark
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	private String wdremark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd.gradeRemark
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	private String graderemark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd.companyName
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	private String companyname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd.contractNo
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	private String contractno;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd.oldTitlePhoto
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	private String oldtitlephoto;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd.wdRemark
	 * 
	 * @return the value of wd.wdRemark
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	public String getWdremark() {
		return wdremark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd.wdRemark
	 * 
	 * @param wdremark
	 *            the value for wd.wdRemark
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	public void setWdremark(String wdremark) {
		this.wdremark = wdremark == null ? null : wdremark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd.gradeRemark
	 * 
	 * @return the value of wd.gradeRemark
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	public String getGraderemark() {
		return graderemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd.gradeRemark
	 * 
	 * @param graderemark
	 *            the value for wd.gradeRemark
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	public void setGraderemark(String graderemark) {
		this.graderemark = graderemark == null ? null : graderemark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd.companyName
	 * 
	 * @return the value of wd.companyName
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	public String getCompanyname() {
		return companyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd.companyName
	 * 
	 * @param companyname
	 *            the value for wd.companyName
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	public void setCompanyname(String companyname) {
		this.companyname = companyname == null ? null : companyname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd.contractNo
	 * 
	 * @return the value of wd.contractNo
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	public String getContractno() {
		return contractno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd.contractNo
	 * 
	 * @param contractno
	 *            the value for wd.contractNo
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	public void setContractno(String contractno) {
		this.contractno = contractno == null ? null : contractno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd.oldTitlePhoto
	 * 
	 * @return the value of wd.oldTitlePhoto
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	public String getOldtitlephoto() {
		return oldtitlephoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd.oldTitlePhoto
	 * 
	 * @param oldtitlephoto
	 *            the value for wd.oldTitlePhoto
	 * 
	 * @mbggenerated Thu Sep 22 15:20:33 CST 2016
	 */
	public void setOldtitlephoto(String oldtitlephoto) {
		this.oldtitlephoto = oldtitlephoto == null ? null : oldtitlephoto.trim();
	}
}