package com.yhq.sqlserver.pojo;

public class WebsiteCalWithBLOBs extends WebsiteCal {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4752340536570695034L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd_cal.ZgId
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	private String zgid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd_cal.OName
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	private String oname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd_cal.PAddress
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	private String paddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd_cal.wdopinion
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	private String wdopinion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd_cal.analysisSummary
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	private String analysissummary;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd_cal.ABCDE
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	private String abcde;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column wd_cal.FGHI
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	private String fghi;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd_cal.ZgId
	 * 
	 * @return the value of wd_cal.ZgId
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public String getZgid() {
		return zgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd_cal.ZgId
	 * 
	 * @param zgid
	 *            the value for wd_cal.ZgId
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public void setZgid(String zgid) {
		this.zgid = zgid == null ? null : zgid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd_cal.OName
	 * 
	 * @return the value of wd_cal.OName
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public String getOname() {
		return oname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd_cal.OName
	 * 
	 * @param oname
	 *            the value for wd_cal.OName
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public void setOname(String oname) {
		this.oname = oname == null ? null : oname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd_cal.PAddress
	 * 
	 * @return the value of wd_cal.PAddress
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public String getPaddress() {
		return paddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd_cal.PAddress
	 * 
	 * @param paddress
	 *            the value for wd_cal.PAddress
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public void setPaddress(String paddress) {
		this.paddress = paddress == null ? null : paddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd_cal.wdopinion
	 * 
	 * @return the value of wd_cal.wdopinion
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public String getWdopinion() {
		return wdopinion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd_cal.wdopinion
	 * 
	 * @param wdopinion
	 *            the value for wd_cal.wdopinion
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public void setWdopinion(String wdopinion) {
		this.wdopinion = wdopinion == null ? null : wdopinion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd_cal.analysisSummary
	 * 
	 * @return the value of wd_cal.analysisSummary
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public String getAnalysissummary() {
		return analysissummary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd_cal.analysisSummary
	 * 
	 * @param analysissummary
	 *            the value for wd_cal.analysisSummary
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public void setAnalysissummary(String analysissummary) {
		this.analysissummary = analysissummary == null ? null : analysissummary.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd_cal.ABCDE
	 * 
	 * @return the value of wd_cal.ABCDE
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public String getAbcde() {
		return abcde;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd_cal.ABCDE
	 * 
	 * @param abcde
	 *            the value for wd_cal.ABCDE
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public void setAbcde(String abcde) {
		this.abcde = abcde == null ? null : abcde.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column wd_cal.FGHI
	 * 
	 * @return the value of wd_cal.FGHI
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public String getFghi() {
		return fghi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column wd_cal.FGHI
	 * 
	 * @param fghi
	 *            the value for wd_cal.FGHI
	 * 
	 * @mbggenerated Fri Sep 23 12:48:48 CST 2016
	 */
	public void setFghi(String fghi) {
		this.fghi = fghi == null ? null : fghi.trim();
	}
}